/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.yacc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class YaccStandaloneSetup extends YaccStandaloneSetupGenerated {

	def static void doSetup() {
		new YaccStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
