/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.yacc


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class YaccRuntimeModule extends AbstractYaccRuntimeModule {
}
