/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.yacc.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class YaccUiModule extends AbstractYaccUiModule {
}
